cuda_chunk_size: 2900
particles_ti_root: 1000
save_dir: save_dir/interacting_custom
local_dir: /home/tanmay/thesis/UniPhy
dataset_dir: oracle_Data/elastic_torus_orig
camera_json_path: None
image_dir: None
nn_activation: gelu
hidden_size: 128
embed_dim: 128
load_model: save_dir/pretrg/model_51.pth
traj_latent_path: save_dir/pretrg/traj_latent_51.pth
batch_size: 32
lr: 1e-2
step_lr_step_size: 10000
epochs: 500
gt_X_file: None
fproj_load_model: None
latent_init_config: None
material_type_dir: None
object_scale_factor: 0.25
psc: False
wandb_name: particle_pos_loss
latent_idx: None
traj_latent_idx: None
hou_vis: False
traj_data_dir: dataset/interacting_diverse/diverse_horizontalright_mu2030533.5478969873_lam684014.5633939297_fa0.3206971388350998
num_materials: 2
use_kan: false
n_hidden: [3, 2, 1]
n_hidden_ann: 8
grid_range: [[-5.0, 25.0], [-5.0, 25.0], [-5.0, 25.0]]